
transform_tolerance: 0.3
#footprint: [[0.23,-0.165], [-0.23, -0.165], [-0.23, 0.165], [0.23, 0.165]]
#footprint: [[0.20,-0.10], [-0.20, -0.10], [-0.20, 0.10], [0.20, 0.10]]
footprint: [[-0.325,-0.10], [0.075, -0.10], [0.075, 0.10], [-0.325, 0.10]]
#robot_radius: ir_of_robot

max_obstacle_height: 0.40  # assume something like an arm is mounted on top of the robot

map_type: voxel

obstacle_layer:
  enabled:              true
  max_obstacle_height:  0.40
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             2
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 2.5
  raytrace_range: 3.0
  publish_voxel_map: false
  observation_sources:  scan
  scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    min_obstacle_height: 0.0
    max_obstacle_height: 0.40

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  inflation_radius:     0.35  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
